### ISSUE TITLE
Error "the server could not find the requested resource (get pods.metrics.k8s.io)" with service account

### ISSUE THREAD

**Issue by Evantage-WS** [wangjia184/pod-inspector#1]
Hello,

I have given the default service account cluster-admin permissions, but when using it, I do get the error:

```
the server could not find the requested resource (get pods.metrics.k8s.io)
```

It is a cluster without any metrics server.

Could you please take a look at this?

**Comment by wangjia184** [comment]
Thanks for raising this issue,  yep, it tries to query metrics and merge with pod record. I will try to fix this.

**Comment by Evantage-WS** [comment]
Great, thanks. Next to this, it would be nice that we can use another serviceaccount rather than de default one, the default one should remain untouched. Can you give a list of permissions which the serviceaccount needs, I do not want to give it admin persmissions.

**Comment by wangjia184** [comment]
@ws-prive  a new version is released. Now metrics are optional. If it is not available, a question mark `?` is presented.

Regarding running pod using another serviceaccount, this was already supported. This tool does not bind to the default service account. You may find the document [here](https://github.com/wangjia184/pod-inspector/blob/master/README.md#use-a-dedicated-service-account).  

But I don't find a way to grant permission to access Metric API on `Role`.  Since permission on Metric API can only be granted on `ClusterRole` which is not available in my case.

**Comment by Evantage-WS** [comment]
@wangjia184, ok, thanks. The additional serviceaccount is working, without a metricsserver it is also working, the ?? are indeed displayed, but with the K8s metrics server installed, it is still showing ?? due that the metrics api should be present in the role, the solution is to add the following to the role.yaml.
```
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "watch", "list"]
```

The complete role.yaml looks like this:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-inspector
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "watch", "list"]
```
I have done some basic testing, so I could be missing something, but with this config I do get the numbers.
